---
title: "week 8 lab"
author: "Cameron, David, Mikayla, Rachel"
date: "2023-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
```

# Data
```{r }
ChemData<-read_csv(here("week_9","data", "chemicaldata_maunalua.csv"))

glimpse(ChemData)
```

## acidity function


```{r }
pH_level <- function(pH){ 
if(pH<7.0) {
  pH_level <- "acidic"
  } 
  else if (pH>7.0) {
    pH_level <- "basic"
  }
  else if (pH==7.0) {
    pH_level <- "neutral"
  } 
  return(pH_level)
}
pH_level(6)
pH_level(9)
pH_level(7)
```

## graph

```{r}
pH_plot <- function(data, x, y, line= TRUE) {
if(line==TRUE){
  ggplot(data= data,
         aes(x= {{x}},
             y= {{y}}))+ ##graphing by phosphate impact on pH 
  geom_line(color= "#AD7DE8")+
  geom_point()+
  geom_smooth()
}
else{
  ggplot(data= data,
         aes(x= {{x}},
             y= {{y}}))+ ##graphing by phosphate impact on pH
  geom_line(color= "#AD7DE8")+
  geom_point()+
  geom_smooth()
}
}
pH_plot(data=ChemData, x= Phosphate, y=pH)
```



