---
title: "BigFoot Spottings in America"
author: "David"
date: "2023-03-07"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message= TRUE,
                       warning =FALSE,
                       fig.path= "../output/")
```

## library
libraries used
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
library(kableExtra)
```

## Manually inputting data
import data set of bigfoot
```{r}

bigfoot <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-13/bigfoot.csv')

glimpse(bigfoot)
```


##  filtered data

Bigfoot data filtered to get rid of Alaska plots, unknown seasons, and outliers due to false data points.

```{r pressure, echo=FALSE}
filtered_bigfoot <- bigfoot%>%
  drop_na(latitude,
          season) %>%
  filter(state != "Alaska",
         season != "Unknown",
         longitude > -140)
```


## plotted data
plot of bigfoot sightings in USA excluding Alaska
```{r}
glimpse(filtered_bigfoot)
states <- map_data("state") ##import US map
ggplot()+
  geom_polygon(data= states, #data using for map
               aes(x= long,
                   y= lat, 
                   group= group,
                   fill = region))+ ##coloring states
  geom_point(data= filtered_bigfoot,  #bigfoot data to go into map
             aes(x= longitude,
                 y= latitude),
             color="black",  #creating black marks for spots location od sightings 
             alpha = 0.5)+  #make the marks transparent
  facet_wrap(~season)+  #create different graphs by seasons
  labs(x= "Longitude", #rename x axes
       y= "Laditude", #rename y axes
       title= "Sight Spottings of Bigfoot in America Excluding Alaska")+ #change title
  theme(legend.position = "none")
```
