---
title: "Penguin Script"
author: "David"
date: "2023-02-28"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: dark
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message= FALSE,
                      warning=FALSE)
```

## Introduction

Today we are going to work with the penguin data to learn *Rmarkdown*

# load library
```{r}
library(here)
library(tidyverse)
library(palmerpenguins)
```


# inspect the data 
```{r}
glimpse(penguins) #look at the penguin data
```




# make a plot  
plot the penguin with bill length by bill depth

```{r}
penguins %>%
  ggplot(aes(x=bill_length_mm,
             y= bill_depth_mm,
             color= species))+
  geom_point()+
  geom_smooth(method= "lm")+
  labs(x= "Bill Length (mm)",
       y= "Bill Depth (mm)",
       color= "Species")+
  theme()
```



```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
