---
title: "penguins"
author: "David"
date: "2023-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr:: opts_chunk$set(echo= TRUE,
                       message= FALSE,
                       warning =FALSE,
                       fig.path= "../output/")
```

# library
```{r}
library(tidyverse)
library(palmerpenguins)
library(here)
library(beyonce)
library(ggthemes)
library(kableExtra)

```

# data
```{r}
glimpse(penguins)
```

## making a plot


```{r penguins, out.put= "50%", fig.cap= "this is de plot", echo= FALSE}
penguins %>%
  ggplot(aes(x= flipper_length_mm,
             y= body_mass_g,
             color= species))+
  geom_line()
```

## making a table
```{r}
  penguins %>%
  group_by(species) %>%
  summarise(flippermean= mean(flipper_length_mm, na.rm= TRUE))%>%
  kbl() %>%
  kable_classic() %>%
  row_spec(2, bold= T, color= "yellow", background= "blue") %>%
  kable_styling(full_width= FALSE)
```
  


You can also embed plots, for exampl

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
